### PR TITLE
Add MonadFree and ComonadCofree

### PR DESCRIPTION
**Pull request by paf31**
I need this for some comonads-as-spaces work I'm doing in `purescript-pairings`.

I think we ought to discuss how to properly give attribution for ported Haskell code before we merge this, since `free` is BSD-3 licensed which would mean switching this repo over to BSD-3 too, and then adding a section to the license file. Thoughts?

### CODE REVIEW

**Comment by paf31** [comment]
Another option here is to move `liftFree` (and `tail`) into the class, but that would be a breaking change.

**Comment by paf31** [comment]
Updated for 0.12 and the new license.

**Comment by garyb** [comment]
LGTM! 👍

**Comment by paf31** [comment]
Ok if I merge and tag a minor update then?

**Comment by garyb** [comment]
Sure thing... I meant to do so but got distracted :smile:

**Pull request merged**
