### PR TITLE
Add foldFree_ variant (for discussion)

### PR DESCRIPTION
**Pull request by garyb**
This function is kinda weird so I'm not sure if it should belong in `free`, but if it doesn't then we'll need to export `toView` so it can be implemented elsewhere.

The comment sums up the idea behind it. Is this a bad idea?

### CODE REVIEW

**Comment by garyb** [comment]
Perhaps I should call it `foldFree'` actually as it's a variation on the original, not one that ignores some input or output.

**Comment by ethul** [comment]
I am definitely open to adding additional functions here. For this one, I wonder if it might be good to call it `foldFreeMaybe`. Too verbose? Also, I am curious if there is a specific use-case you have for this. I'd be interested to see a situation of where it is used.

**Comment by garyb** [comment]
`foldFreeMaybe` is definitely a better name... I'm actually considering whether I do need this or not, I might actually be better off not using `Free` at all for what I'm doing. I'll come back to this when I figure it out for sure!

Basically I have a case where I'm interpreting but don't want to define a match for every constructor in the algebra... so the fact it aborts on `Nothing` isn't particularly desirable, just a consequence of how this has to work. However I think the case I need it for the `Free` structure will only contain one constructor anyway, so therefore I probably don't need `Free` at all. This function definitely works, but I'm not sure it's the best way to solve the problem.

**Comment by garyb** [comment]
Indeed I don't need it! I'll reopen this as `foldFreeMaybe` if it turns out to be useful sometime.

**Comment by ethul** [comment]
Okay. Sounds good.

**Comment by paf31** [comment]
Isn't this a regular fold using MaybeT as the target monad?

Everything we want to export should be definable in terms of the adjunction, I think.

**Comment by garyb** [comment]
Most likely, yep. Good call.

**Pull request closed without merging**
