### PR TITLE
Bump transformers dependency

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb @hdgarrood

### CODE REVIEW

**Comment by paf31** [comment]
The `benchotron` dependency needs to be updated too, since `benchotron` uses `quickcheck`.

**Comment by paf31** [comment]
We have a potentially big issue with 0.7.4 and `-inject`. `injectLeft` and `injectRight` are _necessarily overlapping instances_ under the new scheme. I've removed the test for now, but we need to figure out a plan to solve this.

**Comment by garyb** [comment]
That's... not good. I did wonder about `Inject` last night after I went offline.

**Comment by garyb** [comment]
I think the way this works in Haskell is by using `OverlappingInstances`.

This looks like an interesting approach that is less dodgy, but would be much more involved: http://web.cecs.pdx.edu/~mpj/pubs/instancechains.pdf

**Comment by garyb** [comment]
A potential (temporary, poor) fix: warn sternly on overlapping instances and just take the first option.

**Comment by garyb** [comment]
Another temporary poor fix but perhaps slightly less so: make an exception for `Inject`.

I'm not sure what's going on with the overlap in the PSCI support module though...

**Comment by paf31** [comment]
I know how to fix the PSCi issue, but `Inject` is a genuine problem.

Some options:

- Get rid of `Inject` the class, and introduce `Inject` the data type (`Category`, `Choice`, etc.) This is my preferred option if we're doing "what's right for the language and libraries" but I know this breaks a lot of existing code.
- Allow overlaps everywhere with a warning. I prefer this to making special cases.
- Revert to the previous code. This is my least favorite option and I'd really rather avoid it, since there are additional benefits to the new changes (the simplification makes it easier to optimize the lookup for example).

**Pull request merged**
