### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by JordanMartinez**
Backlinking to purescript/purescript#3942

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Currently blocked by `exists` and likely some kind signature warnings, but I won't know what they are until `exists` is updated.

**Comment by JordanMartinez** [comment]
`purescript-benchotron` is not a core repo. By including it here, this repo will never pass CI because benchotron will pull in non-master dependencies.

This should be re-added later. Before merging this PR, we need to add an issue that tracks this.

Also, we will need to decide whether to merge #104 or not before or after this one.

**Review by thomashoneyman — APPROVED** [review]
Can you open an issue to re-enable benchmarks after this closes and link it to an issue on benchotron for updating to 0.14?

**Comment by JordanMartinez** [comment]
I've opened issues in this repo and the benchotron one.

**Pull request merged**
