### PR TITLE
Update purescript-control to a version that actually exists

### PR DESCRIPTION
**Pull request by jdegoes**

### CODE REVIEW

**Comment by jdegoes** [comment]
The bower file references a version of purescript-control which does not exist.

**Comment by garyb** [comment]
Yeah, it's intentional, the core libraries are in an inbetween state as they're being updated as one batch for the 0.7 compiler. I'm going to make an interim release with the fix from a branch.

**Comment by jdegoes** [comment]
Thanks!

**Comment by garyb** [comment]
This should be sorted now.

**Pull request closed without merging**
