### PR TITLE
Export `Cofree` constructor

### LINKED ISSUE #90: Expose `Cofree` constructor
Currently there's no way to make a single lazy Cofree node since the constructor is not exported, and mkCofree is strict.

### PR DESCRIPTION
**Pull request by natefaubion**
Fixes #90

### CODE REVIEW

**Comment by paulyoung** [comment]
Ignoring backwards compatibility for a moment, is there a some benefit to keeping `mkCofree` around as opposed to using the `Cofree` constructor everywhere instead (including the `:<` operator)?

**Comment by garyb** [comment]
It's still useful when you don't care about it being lazy, I think.

**Comment by paf31** [comment]
Thinking about this a bit more, what about adding a `Lazy` instance, and optionally moving the `a` under the `Lazy`?

**Comment by paulyoung** [comment]
@natefaubion any thoughts on Phil's suggestion? 

Does this make any difference to the use case we were discussing of implementing a `union` function using `unfoldCofree`?

**Comment by natefaubion** [comment]
@paf31 You mean something like

```purescript
newtype Cofree f a = Cofree (Lazy (Tuple a (Lazy (Cofree f a)))

instance lazyCofree :: Lazy (Cofree f a) where
  defer k = Cofree $ Z.defer \_ ->
    let (Cofree thunk) = k unit in Z.force thunk
```

@paulyoung no this would make no difference to what we talked about. A lazy instance lets you create cycles in the graph.

**Comment by paf31** [comment]
Yes something like that. Would that let us keep the constructor hidden for your use case?

**Comment by natefaubion** [comment]
How lazy would you want it:

```purescript
newtype Cofree f a = Cofree (Lazy (Tuple a (f (Cofree f a))))
```

```purescript
newtype Cofree f a = Cofree (Lazy (Tuple a (Lazy (f (Cofree f a)))))
```

The second is an awful lot of boxing, but you may not want to strictly assemble the f. `Free` doesn't use any sort of laziness, so maybe the first is appropriate.

**Comment by natefaubion** [comment]
I would rather then just export a function like:
```cofree :: forall f a. Functor f => (Unit -> Tuple a (f (Cofree f a))) -> Cofree f a```
Because otherwise using `defer` would always result in an extra unnecessary box. That's one of my frustrations with some `Lazy` instances (like for `Lazy` itself).

**Comment by paf31** [comment]
I'm fine with that too 👍

**Comment by natefaubion** [comment]
Closing in favor of #92

**Pull request closed without merging**
