### PR TITLE
Topic/benchotron

### PR DESCRIPTION
**Pull request by ethul**
This PR incorporates benchotron benchmarks and does some reworking of the tests.

### CODE REVIEW

**Comment by garyb** [comment]
Looks like the travis build is failing because `benchotron` needs updating for psc v0.7.3-compatible-dependencies (`-string` v0.7.0).

**Comment by ethul** [comment]
Good catch @garyb. Thanks.

@hdgarrood would you like a PR for this?

**Comment by hdgarrood** [comment]
I've released a new version of benchotron which should use up-to-date versions of dependencies. Unfortunately, benchotron now uses quickcheck for generating input data, which is not currently stack-safe, so this is probably blocked on purescript/purescript-quickcheck#37 now.

**Comment by ethul** [comment]
@hdgarrood Thanks for making the 3.0.0 release. Thanks for pointing out purescript/purescript-quickcheck#37. 

@garyb What do you think? Since I already have the benchmarks generated, would you prefer I wait for purescript/purescript-quickcheck#37 or just update with benchotron @ 3.0.0?

**Comment by garyb** [comment]
@hdgarrood Oh sorry, I hadn't realised you'd rebased that.

I'll merge and release now, and then we can get everything up to date :)

**Comment by hdgarrood** [comment]
Awesome, thanks. I'll release a 3.0.1 which depends on the newest quickcheck.

**Comment by ethul** [comment]
@hdgarrood Thanks!

**Comment by hdgarrood** [comment]
Ok, that's done, so if you depend on 3.0.1 then this should work. I guess you could replace `zeroArray` with `\n -> vectorOf n (pure 0)`.

**Comment by ethul** [comment]
@hdgarrood Great! Thanks. Yes, that is what I did for the `zeroArray`

**Comment by hdgarrood** [comment]
:smile: no problem

**Comment by ethul** [comment]
@garyb Looks like the dependencies update did the trick. What do you think? Are we good to go for this?

**Comment by garyb** [comment]
Yep, thanks a lot for your work on all this! I'll make a release.

**Comment by ethul** [comment]
Great, thank you!

**Pull request merged**
