### PR TITLE
Added `Functor f => MonadRec (Free f)` instance.

### PR DESCRIPTION
**Pull request by LiamGoodacre**

### CODE REVIEW

**Comment by jdegoes** [comment]
:+1:

**Comment by garyb** [comment]
:+1: 

If we'd had this, I wouldn't have needed that `bindF` stuff I think, hah.

**Comment by LiamGoodacre** [comment]
#37 also has this (written in a nicer way), should we close this PR?

**Comment by garyb** [comment]
I thought I'd already merged this actually. I'll do so now anyway as we can release this as a minor bump whereas the new approach will be a breaking change. Thanks!

**Pull request merged**
